name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv git

      - name: Set up Python
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[test]"

      - name: Run tests
        run: pytest --cov=flaskpp
